src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 */
class Property
{

    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floar;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options= {"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdat;

    public function __construct()
    {
        $this -> createdat = new\DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug()
    {
        return (new Slugify())->slugify($this->title); 
          
    }
    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloar(): ?int
    {
        return $this->floar;
    }

    public function setFloar(int $floar): self
    {
        $this->floar = $floar;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormatedPrice ()             // formate du prix, pour mettre un espace entre les chiffres
    {
        return number_format($this->price, 0,'',' ');
    }
    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType()
    {
        return self::HEAT[$this->heat];
    }
    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedat(): ?\DateTimeInterface
    {
        return $this->createdat;
    }

    public function setCreatedat(\DateTimeInterface $createdat): self
    {
        $this->createdat = $createdat;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floar')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()                                        // Property::HEAT pour recuperer la fonction que j'avais crée mais le choix ne m'arrange pas car le label me donne 0 ou 1 
            ])
            ->add('city')
            ->add('adress')
            ->add('postal_code')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    public function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $k => $v) {
            $output[$v] = $k;
        }

        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Property;
use App\Repository\PropertyRepository;
use Doctrine\Persistence\ObjectManager;

class PropertyController extends AbstractController
{


    /**
     * @var PropertyRepository
     */

    private $propertyRepository;

    public function __construct(PropertyRepository $propertyRepository)
    {
        $this -> repository = $propertyRepository;        
    }


    /**
     * @Route("/biens", name="biens")
     */
    public function index(PropertyRepository $propertyRepository)
    {
        /*                                      Code d'insert;
        $property = new Property();                             Je crée une nouvelle propriété
        $property ->setTitle('Mon premier bien')                Je défini les valeurs de cet proprité
                ->setPrice(200000)
                ->setRooms(4)
                ->setBedrooms(3)
                ->setDescription('Une petite description')
                ->setSurface(60)
                ->setFloar(4)
                ->setHeat(1)
                ->setCity('Montpellier')
                ->setAdress('15 rue de Gambetta')
                ->setPostalCode(34000)
                ;

                $em = $this -> getDoctrine()->getManager();     J'utilise doctrine et le manager pour envoyer en bd
                $em -> persist($property);
                $em -> flush();
        */


       /*       Pour select avec ce que je souhaite en parametre (Where)
       
       $property = $this->repository->findOneBy(['floar' => 4]);
        dump($property);

        */ 
        
        $properties = $propertyRepository->findAllVisible();
        //$property[0]->setSold(true);

        //$this->getDoctrine()->getManager()->flush();
        
        return $this->render('property/index.html.twig', [
            'properties' => $properties
        ]);
    }
    /**
     * @Route ("/biens/{slug}-{id}", name="property_show", requirements={"slug": "[a-z0-9\-]*"})
     * @return response
     */
    public function show($slug, Property $property)
    {
        if ($property->getslug() !== $slug) 
        {
           return $this->redirectToRoute('property_show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ] , 301 );

        }
        return $this->render('property/show.html.twig', [
            'property' => $property            
        ]);
    }
}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les biens | Agence Immo{% endblock %}

{% block body %}

<header class="masthead" style="background-image:url('assets/img/biens.jpg'); height: 70vh;">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <p class="intro-text">A free, responsive, one page Bootstrap theme.<br>Created with love.</p>
                    </div>
                </div>
            </div>
        </div>
</header>

<div class="container mt-5 text-center">
    <h2> Les biens </h2>
    <div class ="row flex">
        {% for property in properties %}
        <div class="col-3">
            <div class= "card">
                <div class="card-body">
                    <h5 class="card-title">
                    <a href=" {{ path('property_show', {'id': property.id, 'slug': property.slug} )}}">{{ property.title }} </a>
                    </h5>
                    <p class="card-text text-dark">{{ property.city }} ({{property.postalCode}})</p>
                    <div class="text-primary">{{ property.FormatedPrice}}$</div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/property/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
    
{% endblock %}

{% block body %}
<div class="jumbotron" style="margin-top: 5rem;border-radius: 0px;">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
            
            </div>
            <div class="col-md-4">
                <h1 class="text-dark">{{ property.title}}</h1>
                <h2 class="text-dark">{{property.rooms}} pièces - {{property.surface }} m²</h2>
                <div class="text-primary" style="font-weight: bold">{{property.formatedPrice}} $</div>
                <a href="" class="btn btn-primary">Contacter l'agence</a>
            </div>
        </div>
    </div>
</div>
    <div class="container mt-5">
        
    

    <p>
        {{ property.description | nl2br }}
    </p>

    <div class="row">
        <div class="col-md-8">
        <h2>Caractéristiques</h2>
            <table class="table table-stripped text-light">
                <tr>
                    <td>Surface habitable</td>
                    <td>{{property.surface}} m²</td>
                </tr>

                <tr>
                    <td>Pièces</td>
                    <td>{{property.rooms}}</td>
                </tr>
                <tr>
                    <td>Chambres</td>
                    <td>{{property.bedrooms}}</td>
                </tr>
                <tr>
                    <td>Etage</td>
                    <td>{{property.floar}}</td>
                </tr>
                <tr>
                    <td>Chauffage</td>
                    <td>{{property.HeatType}}</td>
                </tr>
            </table>
        </div>
        <div class="col-md-4">
            <h2>Spécificités</h2>
        </div>
    </div>
</div>
{% endblock %}